version: '3.7'

networks:
  app-tier:
    name: app-tier

services:
  mongodb:
    image: mongo:3.6.15-xenial
    container_name: mongodb
    hostname: mongodb
    volumes:
      - /data/mongoDB:/data/db
      - /data/mongoDB:/data/configdb
    environment:
      MONGODB_USERNAME: dbbmf
      MONGODB_PASSWORD: dbbmf
      MONGODB_DBNAME: dbbmf
    ports:
      - "27017:27017"
    networks:
      - app-tier