version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - /data/mongoDB:/data/db
      - /data/mongoDB:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbbmf
      MONGO_INITDB_ROOT_PASSWORD: dbbmf
      MONGO_INITDB_DATABASE: dbbmf_bff
    ports:
      - "27017:27017"