version: '3.7'

networks:
  app-tier:
    name: app-tier

services:
  mongodb:
    image: mongo:3.6.15-xenial
    container_name: mongodb
    hostname: mongodb
    volumes:
      - /data/mongoDB:/data/db
      - /data/mongoDB:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbbmf
      MONGO_INITDB_ROOT_PASSWORD: dbbmf
    ports:
      - "27017:27017"
    networks:
      - app-tier

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /data/rabbitMQ:/data
    networks:
      - app-tier
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
      RABBITMQ_DEFAULT_VHOST: personal